<a href="https://colab.research.google.com/github/diwakardixit/Data_Science/blob/main/TextProcessingNLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

In [17]:
import pandas as pd
with open("Data1.txt", 'r') as f:
  lines = f.readlines()
df = pd.DataFrame(lines, columns=['text_content'])
display(df.head())

                                        text_content
0  The Strait of Hormuz (/hɔːrˈmuːz/)[a] is a wat...
1   On the north coast lies Iran, and on the sout...
2  Governorate of Oman, with a portion of the sou...
3   The strait is about 104 miles (90 nmi; 167 km...
4   (52 nmi; 97 km) to 24 mi (21 nmi; 39 km).[1][...

In [18]:
df.shape

(17, 1)

In [19]:
df['text_content'] = df['text_content'].str.lower()

In [20]:
df

                                         text_content
0   the strait of hormuz (/hɔːrˈmuːz/)[a] is a wat...
1    on the north coast lies iran, and on the sout...
2   governorate of oman, with a portion of the sou...
3    the strait is about 104 miles (90 nmi; 167 km...
4    (52 nmi; 97 km) to 24 mi (21 nmi; 39 km).[1][...
5                                                  \n
6   it provides the only sea passage from the pers...
7    most strategically important choke points.[3]...
8    gas (lng) and 25% of seaborne oil trade passe...
9    petroleum products for europe and asia and ha...
10  [4] it is also the only maritime route for sev...
11   kuwait and iraq and disruption to the strait ...
12                                                 \n
13  the strait has traditionally never been closed...
14  (unlike the straits of tiran/bab-el-mandeb)[6]...
15  strait,[7][8] and preparations to mine it have...
16   focus during the 2026 iran war, resulting in ...

Removing HTML Tags

In [21]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [22]:
df['text_content'] = df['text_content'].apply(remove_html_tags)

In [23]:
df['text_content'][15]

'strait,[7][8] and preparations to mine it have been undertaken.[9] the strait has become a major\n'

Removing link text

In [24]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)

In [25]:
df['text_content'] = df['text_content'].apply(remove_url)
df['text_content']

0     the strait of hormuz (/hɔːrˈmuːz/)[a] is a wat...
1      on the north coast lies iran, and on the sout...
2     governorate of oman, with a portion of the sou...
3      the strait is about 104 miles (90 nmi; 167 km...
4      (52 nmi; 97 km) to 24 mi (21 nmi; 39 km).[1][...
5                                                    \n
6     it provides the only sea passage from the pers...
7      most strategically important choke points.[3]...
8      gas (lng) and 25% of seaborne oil trade passe...
9      petroleum products for europe and asia and ha...
10    [4] it is also the only maritime route for sev...
11     kuwait and iraq and disruption to the strait ...
12                                                   \n
13    the strait has traditionally never been closed...
14    (unlike the straits of tiran/bab-el-mandeb)[6]...
15    strait,[7][8] and preparations to mine it have...
16     focus during the 2026 iran war, resulting in ...
Name: text_content, dtype: object

Removing Bracketed Numbers/Citations

In [26]:
df['text_content'] = df['text_content'].str.replace(r'\[\d+\]', '', regex=True)

Removing \n

In [27]:
df['text_content'] = df['text_content'].str.replace('\n','')

Removing punctuation

In [28]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [29]:
exclude = string.punctuation

In [30]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,'')
  return text

In [31]:
df['text_content'] = df['text_content'].apply(remove_punc)

In [32]:
df['text_content']

0     the strait of hormuz hɔːrˈmuːza is a waterway ...
1      on the north coast lies iran and on the south...
2     governorate of oman with a portion of the sout...
3      the strait is about 104 miles 90 nmi 167 km l...
4                    52 nmi 97 km to 24 mi 21 nmi 39 km
5
6     it provides the only sea passage from the pers...
7      most strategically important choke points dur...
8      gas lng and 25 of seaborne oil trade passed t...
9      petroleum products for europe and asia and ha...
10     it is also the only maritime route for severa...
11     kuwait and iraq and disruption to the strait ...
12
13    the strait has traditionally never been closed...
14    unlike the straits of tiranbabelmandeb though ...
15    strait and preparations to mine it have been u...
16     focus during the 2026 iran war resulting in t...
Name: text_content, dtype: object

In [33]:
import nltk

In [34]:
from nltk.corpus import stopwords

In [35]:
nltk.download ("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [36]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [37]:
st=stopwords.words('english')

In [38]:
st

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [39]:
df2=''

In [40]:
for text_entry in df['text_content']:
  # Ensuring text_entry is a string before splitting
  if isinstance(text_entry, str):
    words = text_entry.split()
    for word in words:
      if word not in st:
        df2 += word + ' '

In [41]:
df2

'strait hormuz hɔːrˈmuːza waterway persian gulf gulf oman north coast lies iran south coast lies musandam peninsula musandam governorate oman portion southwest peninsula united arab emirates strait 104 miles 90 nmi 167 km long width varying 60 mi 52 nmi 97 km 24 mi 21 nmi 39 km provides sea passage persian gulf open ocean one worlds strategically important choke points 2023–2025 20 worlds liquefied natural gas lng 25 seaborne oil trade passed strait annually major source petroleum products europe asia described critical europes energy security also maritime route several gulf countries including uae qatar bahrain kuwait iraq disruption strait cause severe supply shortages strait traditionally never closed extended time middle east conflicts unlike straits tiranbabelmandeb though iran occasionally threatened close strait preparations mine undertaken strait become major focus 2026 iran war resulting strait hormuz crisis '

In [42]:
tokens = re.findall("[\w']+",df2)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1549/542383077.py:1: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+",df2)

In [43]:
tokens

['strait',
 'hormuz',
 'hɔːrˈmuːza',
 'waterway',
 'persian',
 'gulf',
 'gulf',
 'oman',
 'north',
 'coast',
 'lies',
 'iran',
 'south',
 'coast',
 'lies',
 'musandam',
 'peninsula',
 'musandam',
 'governorate',
 'oman',
 'portion',
 'southwest',
 'peninsula',
 'united',
 'arab',
 'emirates',
 'strait',
 '104',
 'miles',
 '90',
 'nmi',
 '167',
 'km',
 'long',
 'width',
 'varying',
 '60',
 'mi',
 '52',
 'nmi',
 '97',
 'km',
 '24',
 'mi',
 '21',
 'nmi',
 '39',
 'km',
 'provides',
 'sea',
 'passage',
 'persian',
 'gulf',
 'open',
 'ocean',
 'one',
 'worlds',
 'strategically',
 'important',
 'choke',
 'points',
 '2023',
 '2025',
 '20',
 'worlds',
 'liquefied',
 'natural',
 'gas',
 'lng',
 '25',
 'seaborne',
 'oil',
 'trade',
 'passed',
 'strait',
 'annually',
 'major',
 'source',
 'petroleum',
 'products',
 'europe',
 'asia',
 'described',
 'critical',
 'europes',
 'energy',
 'security',
 'also',
 'maritime',
 'route',
 'several',
 'gulf',
 'countries',
 'including',
 'uae',
 'qatar',
 'bahrain',
 'kuwait',
 'iraq',
 'disruption',
 'strait',
 'cause',
 'severe',
 'supply',
 'shortages',
 'strait',
 'traditionally',
 'never',
 'closed',
 'extended',
 'time',
 'middle',
 'east',
 'conflicts',
 'unlike',
 'straits',
 'tiranbabelmandeb',
 'though',
 'iran',
 'occasionally',
 'threatened',
 'close',
 'strait',
 'preparations',
 'mine',
 'undertaken',
 'strait',
 'become',
 'major',
 'focus',
 '2026',
 'iran',
 'war',
 'resulting',
 'strait',
 'hormuz',
 'crisis']

In [44]:
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [45]:
word_tokenize(df2)

['strait',
 'hormuz',
 'hɔːrˈmuːza',
 'waterway',
 'persian',
 'gulf',
 'gulf',
 'oman',
 'north',
 'coast',
 'lies',
 'iran',
 'south',
 'coast',
 'lies',
 'musandam',
 'peninsula',
 'musandam',
 'governorate',
 'oman',
 'portion',
 'southwest',
 'peninsula',
 'united',
 'arab',
 'emirates',
 'strait',
 '104',
 'miles',
 '90',
 'nmi',
 '167',
 'km',
 'long',
 'width',
 'varying',
 '60',
 'mi',
 '52',
 'nmi',
 '97',
 'km',
 '24',
 'mi',
 '21',
 'nmi',
 '39',
 'km',
 'provides',
 'sea',
 'passage',
 'persian',
 'gulf',
 'open',
 'ocean',
 'one',
 'worlds',
 'strategically',
 'important',
 'choke',
 'points',
 '2023–2025',
 '20',
 'worlds',
 'liquefied',
 'natural',
 'gas',
 'lng',
 '25',
 'seaborne',
 'oil',
 'trade',
 'passed',
 'strait',
 'annually',
 'major',
 'source',
 'petroleum',
 'products',
 'europe',
 'asia',
 'described',
 'critical',
 'europes',
 'energy',
 'security',
 'also',
 'maritime',
 'route',
 'several',
 'gulf',
 'countries',
 'including',
 'uae',
 'qatar',
 'bahrain',
 'kuwait',
 'iraq',
 'disruption',
 'strait',
 'cause',
 'severe',
 'supply',
 'shortages',
 'strait',
 'traditionally',
 'never',
 'closed',
 'extended',
 'time',
 'middle',
 'east',
 'conflicts',
 'unlike',
 'straits',
 'tiranbabelmandeb',
 'though',
 'iran',
 'occasionally',
 'threatened',
 'close',
 'strait',
 'preparations',
 'mine',
 'undertaken',
 'strait',
 'become',
 'major',
 'focus',
 '2026',
 'iran',
 'war',
 'resulting',
 'strait',
 'hormuz',
 'crisis']

In [46]:
sent_tokenize(df2)

['strait hormuz hɔːrˈmuːza waterway persian gulf gulf oman north coast lies iran south coast lies musandam peninsula musandam governorate oman portion southwest peninsula united arab emirates strait 104 miles 90 nmi 167 km long width varying 60 mi 52 nmi 97 km 24 mi 21 nmi 39 km provides sea passage persian gulf open ocean one worlds strategically important choke points 2023–2025 20 worlds liquefied natural gas lng 25 seaborne oil trade passed strait annually major source petroleum products europe asia described critical europes energy security also maritime route several gulf countries including uae qatar bahrain kuwait iraq disruption strait cause severe supply shortages strait traditionally never closed extended time middle east conflicts unlike straits tiranbabelmandeb though iran occasionally threatened close strait preparations mine undertaken strait become major focus 2026 iran war resulting strait hormuz crisis']

Removing Inflection(Stemming Method)

In [47]:
# from nltk.stem.porter immport PorterStemmer
# ps=PorerStemmer()

# def port_stem(text):
#     return" ".join([ps.stem(word) for word in text.split()])

In [48]:
# port_stem(text=df2)

Removing Inflection(Lemmatization Method)

In [49]:
from nltk.stem import WordNetLemmatizer
wnl= WordNetLemmatizer()

In [50]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [51]:
def lemmatize_text(text):
  words = text.split()
  lemmatized_words = [wnl.lemmatize(word) for word in words]
  return ' '.join(lemmatized_words)

lemmatize_df2 = lemmatize_text(df2)
print(lemmatize_df2)

strait hormuz hɔːrˈmuːza waterway persian gulf gulf oman north coast lie iran south coast lie musandam peninsula musandam governorate oman portion southwest peninsula united arab emirate strait 104 mile 90 nmi 167 km long width varying 60 mi 52 nmi 97 km 24 mi 21 nmi 39 km provides sea passage persian gulf open ocean one world strategically important choke point 2023–2025 20 world liquefied natural gas lng 25 seaborne oil trade passed strait annually major source petroleum product europe asia described critical europe energy security also maritime route several gulf country including uae qatar bahrain kuwait iraq disruption strait cause severe supply shortage strait traditionally never closed extended time middle east conflict unlike strait tiranbabelmandeb though iran occasionally threatened close strait preparation mine undertaken strait become major focus 2026 iran war resulting strait hormuz crisis